Document: ibeacon
Title: Debian ibeacon Manual
Author: <insert document author here>
Abstract: This manual describes what ibeacon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ibeacon/ibeacon.sgml.gz

Format: postscript
Files: /usr/share/doc/ibeacon/ibeacon.ps.gz

Format: text
Files: /usr/share/doc/ibeacon/ibeacon.text.gz

Format: HTML
Index: /usr/share/doc/ibeacon/html/index.html
Files: /usr/share/doc/ibeacon/html/*.html
